---
# tasks file for akkerman.swarm

- name: get service facts
  service_facts:

- name: check docker is installed
  fail:
    msg: Please install and start docker first
  when: ansible_facts.services["docker.service"] is not defined

- name: check swarm mode status
  command: 'docker info'
  register: 'docker_info'
  changed_when: false
  check_mode: no

- name: set swarm facts
  set_fact:
    docker_swarm_inactive: "{{ 'Swarm: inactive' in docker_info.stdout }}"
    docker_swarm_ip: "{{ vars['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"

- name: initialize swarm on leader
  command: 'docker swarm init --advertise-addr {{ hostvars[docker_swarm_leader]["docker_swarm_ip"] }}'
  when:
    - docker_swarm_inactive
    - inventory_hostname == docker_swarm_leader

- name: capture manager join token
  command: 'docker swarm join-token -q manager'
  changed_when: false
  register: 'docker_swarm_join_token_manager'
  when: inventory_hostname == docker_swarm_leader

- name: capture worker join token
  command: 'docker swarm join-token -q worker'
  changed_when: false
  register: 'docker_swarm_join_token_worker'
  when: inventory_hostname == docker_swarm_leader

- name: join manager to cluster
  command: >
    docker swarm join
    --token {{ hostvars[docker_swarm_leader]['docker_swarm_join_token_manager'].stdout }}
    {{ hostvars[docker_swarm_leader]["docker_swarm_ip"] }}:2377
  when:
    - docker_swarm_inactive
    - inventory_hostname != docker_swarm_leader
    - "'docker_swarm_managers' in group_names"

- name: join worker to cluster
  command: >
    docker swarm join
    --token {{ hostvars[docker_swarm_leader]['docker_swarm_join_token_worker'].stdout }}
    {{ hostvars[docker_swarm_leader]["docker_swarm_ip"] }}:2377
  when:
    - docker_swarm_inactive
    - inventory_hostname != docker_swarm_leader
    - "'docker_swarm_workers' in group_names"
